spring.application.name=AssetTracker

server.port=${SERVER_PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI:mongodb://supportAppUser:SupportApp123!@localhost:27017/support_desk_db?authSource=support_desk_db}

spring.data.mongodb.auto-index-creation=true

spring.jackson.serialization.indent-output=true
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-stacktrace=always

logging.level.root=INFO
logging.level.com.example.assettracker=DEBUG
